apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet2cattle-hook
spec:
  replicas: 1
  selector:
    matchLabels:
      component: pet2cattle-hook
  template:
    metadata:
      labels:
        component: pet2cattle-hook
    spec:
      containers:
      - name: pet2cattle
        image: rmccarth/slixperi-mutating-webhook:5
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8443
        volumeMounts:
        - name: ssl-pet2cattle-webhook
          mountPath: /ssl
      volumes:
      - name: ssl-pet2cattle-webhook
        configMap:
          name: ssl-pet2cattle-webhook