apiVersion: v1                                   
kind: Pod                            
metadata:         
  name: webserver
  labels:
    test: test-blah
spec:              
  containers:
  - name: webserver 
    image: curlimages/curl:latest
    command: ["tail"]
    args: ["-f", "/dev/null"]
    ports:  
    - containerPort: 80